### ISSUE TITLE
Local variables in sync methods are not visible in the VS debugger 

### ISSUE THREAD

**Issue by DaemonSharps** [pamidur/aspect-injector#217]
**Environment:**
 - OS: windows
 - Framework: net6.0
 - Type of application: Nunit Test Application
 - Version of AspectInjector: 2.8.1

**Describe the bug**
Local variables are not visible when debugging synchronous methods when using AspectInjector.

**To Reproduce**
I am using example from README
  ```
  [Aspect(Scope.Global)]
  [Injection(typeof(AroundTests_Simple))]
  public class AroundTests_Simple : Attribute
  {
          [Advice(Kind.Around, Targets = Target.Method)]
          public object AroundMethod([Argument(Source.Target)] Func<object[], object> target,
              [Argument(Source.Arguments)] object[] arguments)
          {
              return target(arguments);
          }
      }
  ```

Use with synchronous test method.
```
[TestFixture]
    public class TestClass
    {
        [Test]
        [AroundTests_Simple]
        public void Test()
        {
            var test = 1;

            Assert.True(test == 1);
        }
}
```

And get that exception:
![image](https://github.com/pamidur/aspect-injector/assets/56834210/d00da6f9-512d-4610-812e-159d1e926ead)

But with async method it works correctly:
![image](https://github.com/pamidur/aspect-injector/assets/56834210/71f2250e-5467-4a9e-8bc7-d956353aa7c7)

Additional info:
Old issue for async methods 
https://github.com/pamidur/aspect-injector/issues/71

**Comment by pamidur** [comment]
It is a side effect of the way around method is implemented. I didn't catch it earlier somehow :) 
Asyncs have a bit different implementation thought.
I'll look into it! Thank for the report

**Comment by pamidur** [comment]
please see if 2.8.2-pre3 fixes it for you?

**Comment by DaemonSharps** [comment]
Yes, it`s work!

**Comment by StefH** [comment]
@pamidur 
Can you please release an official **2.8.3** release (and also update `Aspects.Universal` to use this latest fixed version 2.8.3 from `AspectInjector`) ?

**Comment by pamidur** [comment]
I just released 2.8.2 today. It should contain all the latest fixes.
I'll update Aspect.Universal soon

**Comment by StefH** [comment]
@pamidur 
I'm used the `2.8.2` and `2.8.3-pre1` but for some reason I still get the same issue for an exception in a try-catch ?

![image](https://github.com/pamidur/aspect-injector/assets/249938/65f69674-4f0d-44ea-9922-fbb0dc230d04)

Note that this method is synchronous.

---
Could this still be an issue?

**Comment by pamidur** [comment]
I well could. Please reopen the issue, I'll take a look at exception block
behaviour

**Comment by StefH** [comment]
@pamidur - I cannot reopen this issue because I did not create it.

**Comment by pamidur** [comment]
No worries, I'm on it

**Comment by lezar44** [comment]
Hello, 
I've had the same issue with  a WPF project using .Net Core 3.1
Downgrading to version 2.4.1 of aspect-injector solved the issue.
Hope it can help you.

**Comment by StefH** [comment]
> No worries, I'm on it

Did you have time yet to fix this?

**Comment by pamidur** [comment]
still looking into it, sorry, don't have much time recently :(

**Comment by lezar44** [comment]
I've solved this issue with a split of Around Advice in Before and After. And now the debugger works fine : 
```
        [Advice(Kind.Before, Targets = Target.Method)]
        public void BeforeMethod([Argument(Source.Name)] string name, [Argument(Source.Type)] Type instanceType, [Argument(Source.Arguments)] object[] arguments)
```
and
```
        [Advice(Kind.After, Targets = Target.Method)]
        public void AfterMethod([Argument(Source.Name)] string name, [Argument(Source.Type)] Type instanceType, [Argument(Source.Arguments)] object[] arguments, [Argument(Source.ReturnValue)] object result)
```

**Comment by StefH** [comment]
@pamidur 
Is this planned to be fixed?
Did that proposal from @lezar44 work?
